[build]
command = "yarn build"
publish = "build"

# Documentation redirects - specific paths first
[[redirects]]
from = "/docs/getting-started/installation"
to = "https://suites.dev/docs/overview/installation"
status = 301
force = true

[[redirects]]
from = "/docs/getting-started/*"
to = "https://suites.dev/docs/overview/:splat"
status = 301
force = true

# General documentation redirect
[[redirects]]
from = "/docs/*"
to = "https://suites.dev/docs/:splat"
status = 301
force = true

# API reference redirects
[[redirects]]
from = "/api-reference/*"
to = "https://suites.dev/docs/developer-guide/unit-tests/suites-api"
status = 301
force = true

# Redirect all other paths except the homepage
[[redirects]]
from = "/*"
to = "https://suites.dev"
status = 301
force = true
conditions = {Path = ["!/"]}